name: "Deploy to Cluster"

on: 
  push:
    branches: 
      - main

jobs:
  deploy:
    name: "Deploy to Cluster"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v7

  